### ISSUE TITLE
Adding more docs 

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [freezing/learn-cryptography#4]
Hi @freezing 

Should I add notes on RSA and encryption that you have covered in your YT video? 
Maybe a directory regarding the "Basic Concepts/Key Terms" of asymmetric cryptography could work?

Want to know your take on this.

Thanks.

**Comment by freezing** [comment]
Maybe we can add a link to https://techwithnikola.com/blog/cryptography/how-rsa-works/ ?

**Comment by ShubhamJagtap2000** [comment]
Surely!

**Comment by ShubhamJagtap2000** [comment]
> Maybe we can add a link to https://techwithnikola.com/blog/cryptography/how-rsa-works/ ?

Hello @freezing , can you address the PR and review. Thanks.

**Comment by freezing** [comment]
Sure, thanks for reminding me. I thought I've already done this.
